- .appveyor.yml
- .cirrus.yml
- .travis.yml
Test against julia 1.4, 1.5, nightly, but not 1.3.
> ci: Bump julia versions

- src/JultraDark.jl
- src/grids.jl
- test/grids.jl
- test/phase_gradient.jl
- test/runtests.jl
Check that the phase difference between neighbouring cells is no larger
than pi/4.
Check at
- the beginning of a sim
- every time the time step is updated
- the end of a sim
> feat: Check phase gradients

- .github/workflows/ci.yml
- README.md
CI has been unable to upload to coveralls.io.  Disable this and just use
codecov.io.
> ci: Disable coveralls

- Project.toml
- README.md
- examples/init_soliton.jl
- examples/soliton_velocity.jl
- src/JultraDark.jl
- src/grids.jl
- src/output.jl
- src/pencil_grids.jl
- test/evolution.jl
- test/grids.jl
- test/output.jl
- test/runtests.jl
- test/sims/full.jl
- test/sims/soliton_static.jl
> Fix multiprocess parallelism

- src/UltraDark.jl
- test/evolution.jl
Enable user modifications of dynamics.  Add external gravitational fields, dependence on constants.
> Enable user modifications

- src/UltraDark.jl
Rewrite the initialization of rho, Phi to be done in the same way as
phi_whole_step.  This uses preallocated outputs for FFTs and
parallelized loops.
> opt: Rewrite initialization

- src/output.jl
Change `SummaryStatisticsMaxRms` to `SummaryStatisticsMeanMaxRms` and
add the maximum to it.
> fix: SummaryStatisticsMaxRms has no max

- Project.toml
- src/UltraDark.jl
- src/config.jl
- src/phase_diff.jl
Allow user to choose the maximum phase difference and density threshold.
> feat: phase difference options

- src/UltraDark.jl
- src/output.jl
> fix: Export summary types

- Project.toml
- src/UltraDark.jl
- src/output.jl
- src/summary.jl
Move summary to own module.
Allow summaries to depend on constants.
> Summary refactor

- examples/init_soliton.jl
- initialize the correct psi
- remove restriction on grids type
> Fix init soliton

- Project.toml
- src/grids.jl
- src/summary.jl
- test/runtests.jl
- test/summary.jl
Move base definition of total mass to src/grids.jl
> Fix totalmass

- .github/workflows/ci.yml
Don't need to run the main test suite on all branches, just master.  The
other branches get tested when pull requests are made.
> ci: Run main test suite on master and PRs

- .JuliaFormatter.toml
- .github/workflows/JuliaFormatter.yml
- benchmarks/fft.jl
- benchmarks/fft_basic.jl
- benchmarks/step1.jl
- benchmarks/step2.jl
- benchmarks/time_step.jl
- benchmarks/time_step/plot.jl
- benchmarks/time_step/time_step.jl
- docs/make.jl
- examples/init_soliton.jl
- examples/soliton_velocity.jl
- src/UltraDark.jl
- src/config.jl
- src/grids.jl
- src/output.jl
- src/pencil_grids.jl
- src/phase_diff.jl
- src/summary.jl
- src/time_step.jl
- test/evolution.jl
- test/grids.jl
- test/output.jl
- test/phase_gradient.jl
- test/runtests.jl
- test/sims/full.jl
- test/sims/soliton_static.jl
- test/summary.jl
Add an action that runs JuliaFormatter on the project.
> ci: Add JuliaFormatter action for github

- test/Project.toml
- test/runtests.jl
Run all Aqua tests other than checking for method ambiguities.  That will have to wait.
> test: Use Aqua

- benchmarks/folds.jl
- src/grids.jl
Fixes https://github.com/musoke/UltraDark.jl/issues/144
> opt: Use Folds.jl for E_grav

- Project.toml
- src/grids.jl
There are functions which calculate radial and angular coordinates from Cartesian.  Use Strided.jl to parallelise them.
> opt: Parallelise calculation of coordinate arrays

- .github/workflows/ci.yml
Use the new Julia-specific cache action instead of the one included from PkgTemplates.jl.
> ci: actions/cache -> julia-actions/cache

- CITATION.cff
- README.md
Add JOSS citation information to README.md and CITATION.cff.
> doc: Add JOSS citation information

- .github/workflows/CI.yml
> ci: Upgrade julia-actions/setup from v1 to v2
