musoke/UltraDark.jl

Project.toml
test/evolution.jl
test/runtests.jl

SafeTestsets separates different tests into modules so they don't leak
into one another.

test: Refactor to use SafeTestsets

---

src/JultraDark.jl

Stop when the time is approximately equal to the end time.

fix: Better stopping condition

---

src/JultraDark.jl

Make the stopping condition in `evolve_to!` more precise.  If there is a
NaN, the stopping condition should be triggered.

fix: Stopping condition in evolve_to!

---

src/JultraDark.jl

The gravitational part of the time step should always be positive but
becomes negative when the gravitational potential is negative.  This can
happen if a sufficiently large fixed background potential is added.
This part of the time step should be such that the phase at any point
never changes by pi during a given time step.  A negative potential
would change the phase in the opposite direction, so should be taken
into account.
Add an absolute value to the time step.
Fixes #31

fix: gravitational timestep

---

src/grids.jl
src/pencil_grids.jl

It is often useful to have arrays of coordinates.
Add arrays of position to Grids.  Each is a 1 x 1 x resol array, so this
doesn't use much more memory.

feat: Add position arrays to Grids

---

.appveyor.yml
.cirrus.yml
.github/workflows/ci.yml

Julia version 1.6 has been released, so test against that.
Also:
- drop 1.4 in github action
- drop 1.4, 1.5, nightly in appveyor

ci: Update to julia 1.6

---

src/grids.jl
src/pencil_grids.jl
test/evolution.jl
test/grids.jl
test/sims/full.jl

Remove the dist array from `Grids` and `PencilGrids`.  This array isn't
needed for anything internal and is a waste of memory.  Using the
position arrays is more practical for anything anyway.

opt: Remove dist from grids structs

---

Project.toml
test/Project.toml

There are a few dependencies that are only needed for tests, not the
library.  Move them to their own Project.toml.

chore: Move test deps to own Project.toml

---

benchmarks/time_step.jl
benchmarks/time_step/time_step.jl
examples/2d.ipynb
examples/mpi/soliton_velocity.jl
examples/soliton_velocity.jl
src/UltraDark.jl
src/config.jl
test/evolution.jl
test/phase_gradient.jl
test/sims/full.jl
test/sims/soliton_static.jl

Using at anonymous function for the scale factor causes a large number
of allocations, due to repeated compilation in a loop.

opt: Remove anonymous a(t) from docs and benches

---

src/UltraDark.jl
src/output.jl
src/phase_diff.jl
src/time_step.jl

Add concrete types in some places and remove abstract types in others.
This takes evolve_to! from millions of allocations to only ~200.

opt: Fix types

---

Project.toml
src/UltraDark.jl
src/output.jl

Allow the user to specify what is written in `summary.csv`.
By default, just the wall time, simulation time, time step and scale
factor.
Technically a breaking change since the max and rms density contrast
aren't output anymore.

feat: Allow user to specify summary

---

examples/init_soliton.jl

The soliton initialisation script has
```
if typeof(grids) == PencilGrids
```
This is useless as it does not match on the type parameters, which
may depend on the pencil decomposition and so are unknown in general.
Instead one should use the subtype operator.
```
if typeof(grids) <: PencilGrids
```

fix: Indexing errors in MPI example

---

test/runtests.jl
test/summary.jl

One of the summary statistics exported from output.jl was named
incorrectly.  Both should be exported from the module as a whole.

fix: export correct summary types

---

src/grids.jl
src/pencil_grids.jl

Define an abstract type `AbstractGrids`.  This is a supertype for other
grids types, allowing dispatch on them more elegantly than dispatch on
`Union{Grids,PencilGrids}`.

refactor: Define type AbstractGrids

---

test/summary.jl

Expand the tests of summaries to include PencilGrids.  This isn't as
comprehensive as it should be, because CI only uses one MPI process, but
better than nothing.

test: Test summaries on PencilGrids too

---

src/UltraDark.jl

The functions `psi_whole_step`, `psi_half_step`, and `phi_step` are
poorly named and have been deprecated for some time.  `outer_step` and
`inner_step` are used instead.
BREAKING CHANGE: `psi_whole_step`, `psi_half_step`, and `phi_step`
deleted.

feat: Delete deprecated functions

---

examples/2d.ipynb
examples/soliton_velocity.jl
src/UltraDark.jl
test/phase_gradient.jl
test/sims/full.jl
test/sims/soliton_static.jl

Conventionally, julia functions that mutate their input have names that
end in `!`.  This was not the case for `simulate`, which mutates the
whole state.  Rename it.
BREAKING CHANGE: simulate -> simulate!

simulate -> simulate!

---

Project.toml
src/pencil_grids.jl

Accidentally left the type signature off of the overloaded definition of angular momentum in 92abcb2b251f12deea24134066c2f597415ee407. Fix this.

fix: Too much overloading of angular momentum

---

src/summary.jl

The doc tests for Summary.WallTime occaisionally fail in CI.  This might be because the two times are generated quickly, so t1 == t2.
Check for t1 <= t2, rather than t1 < t2.

test: Fix overly strong test in summary

---

src/UltraDark.jl
src/output.jl

It is useful to have a list of what times output snapshots correspond to.

feat: Write list of output times to disc

---

Project.toml
src/UltraDark.jl

The symmetrized split step method combines most calls to `outer_step!` with half a time step into full time steps.  However, an extra half step has to be taken each time the time step is updated. This is missing for the external states.
With default settings, this results in an approximately 5% error.
Add it in.

fix: outer_step! call at end of loop missed

---

CITATION.cff

This allows github and zenodo to display metadata more easily.
https://citation-file-format.github.io/

chore: Add CITATION.cff

---

Project.toml
src/UltraDark.jl

There is a missing `; a = a(t)` in the argument to `outer_step!` that does the closing half step.  This is never an issue if there is no background expansion.
Add it in.
This should maybe not be an optional argument; it shouldn't be possible to accidentally call with the wrong `a(t)`.

fix: Correct scale factor on last half step

---

.gitignore
docs/Manifest.toml
docs/Project.toml

Reorganize .gitignore to reflect current practices.  `doc/Manifest.toml` should not be tracked.  It changes when doc environment is rebuilt in different contexts.

chore: Ignore doc/Manifest.toml

---

.github/dependabot.yml

Use dependabot to keep github actions up to date.
See https://github.com/JuliaCI/PkgTemplates.jl/pull/393
Fixes https://github.com/musoke/UltraDark.jl/issues/137

chore: dependabot to update github actions

---

src/config.jl
test/Project.toml
test/runtests.jl
test/sims/scale_factor.jl

Non-constant scale factors were broken some time ago. Fix them and add a test for to avoid silent breakage in future.

fix: Pass non-constant scale factor

---

test/runtests.jl

Initialization of MPI occasionally results in output warning that features are unavailable, etc.  This is not relevant to the doc tests, but can break them by writing to stderr.
Initialize MPI before running any other tests.
Fixes https://github.com/musoke/UltraDark.jl/issues/71

fix(tests): Prevent MPI from breaking doc tests

---

Project.toml
src/grids.jl
test/summary.jl

9b17f3037c4bb013c1aa714cf51383391314d193
(https://github.com/musoke/UltraDark.jl/pull/152) introduced a bug in the gravitational energy.
The arguments of E_gravity_density are reversed.  This doesn't show up in tests because the psi used is real, so the incorrect energy density can be coerced to be real.
Fix this and update the tests of summaries so that psi is complex.

fix: Typo in gravitational energy
